# Generated by Django 6.0 on 2026-01-08 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anioescolar')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.areacurricular')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.centroeducativo')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.grado')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula', models.CharField(max_length=13, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo_personal', models.EmailField(blank=True, max_length=254, null=True)),
                ('codigo_docente_minerd', models.CharField(max_length=50, unique=True)),
                ('area_especialidad', models.CharField(max_length=150)),
                ('fecha_ingreso', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('nombrado', 'Nombrado'), ('contratado', 'Contratado')], max_length=20)),
                ('tanda', models.CharField(choices=[('matutina', 'Matutina'), ('vespertina', 'Vespertina'), ('nocturna', 'Nocturna')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.centroeducativo')),
            ],
        ),
    ]
