# Generated by Django 6.0 on 2026-08-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='docentes/fotos/', verbose_name='Foto'),
        ),
    ]
