# Generated by Django 6.0 on 2026-01-14 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alter_periodo_options_periodo_cerrado_and_more'),
        ('administracion', '0001_initial'),
        ('core', '0002_initial'),
        ('estudiantes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=5)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField()),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anioescolar')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.centroeducativo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grado')),
            ],
            options={
                'unique_together': {('estudiante', 'anio_escolar')},
            },
        ),
    ]
