# Generated by Django 6.0 on 2026-01-14 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_acta'),
        ('core', '0002_initial'),
        ('estudiantes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='acta',
            unique_together={('centro', 'anio_escolar', 'estudiante')},
        ),
        migrations.AddField(
            model_name='acta',
            name='generado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
