# Generated by Django 6.0 on 2026-08-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_acta_unique_together_acta_generado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativo',
            name='cargo',
            field=models.CharField(choices=[('director', 'Director'), ('secretaria', 'Secretaria'), ('cajero', 'Cajero')], max_length=20),
        ),
    ]
