# Generated by Django 6.0 on 2026-08-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_administrativo_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='administrativos/fotos/', verbose_name='Foto'),
        ),
    ]
