# Generated by Django 6.0 on 2026-05-17 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'CREAR'), ('EDITAR', 'EDITAR'), ('ELIMINAR', 'ELIMINAR'), ('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('LOGIN_FAILED', 'LOGIN_FAILED')], max_length=30)),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ruta', models.TextField(blank=True, null=True)),
                ('metodo', models.CharField(blank=True, max_length=10, null=True)),
                ('navegador', models.TextField(blank=True, null=True)),
                ('tipo_dispositivo', models.CharField(blank=True, max_length=20, null=True)),
                ('riesgo', models.CharField(choices=[('BAJO', 'BAJO'), ('MEDIO', 'MEDIO'), ('ALTO', 'ALTO'), ('CRITICO', 'CRITICO')], default='BAJO', max_length=20)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-fecha'],
            },
        ),
    ]
