# Generated by Django 6.0 on 2026-05-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'CREAR'), ('EDITAR', 'EDITAR'), ('ELIMINAR', 'ELIMINAR'), ('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('LOGIN_FAILED', 'LOGIN_FAILED'), ('DESCARGA', 'DESCARGA'), ('PASSWORD_CHANGE', 'PASSWORD_CHANGE'), ('ACCESO_DENEGADO', 'ACCESO_DENEGADO'), ('EXPORTAR', 'EXPORTAR'), ('IMPORTAR', 'IMPORTAR')], max_length=30),
        ),
    ]
