# Generated by Django 6.0 on 2026-08-06 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alter_bitacora_accion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['fecha'], name='auditoria_b_fecha_a31deb_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['usuario', 'fecha'], name='auditoria_b_usuario_935b3e_idx'),
        ),
    ]
