# Generated by Django 6.0 on 2026-08-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_bitacora_auditoria_b_fecha_a31deb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'CREAR'), ('EDITAR', 'EDITAR'), ('ELIMINAR', 'ELIMINAR'), ('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('LOGIN_FAILED', 'LOGIN_FAILED'), ('DESCARGA', 'DESCARGA'), ('PASSWORD_CHANGE', 'PASSWORD_CHANGE'), ('ACCESO_DENEGADO', 'ACCESO_DENEGADO'), ('EXPORTAR', 'EXPORTAR'), ('IMPORTAR', 'IMPORTAR'), ('ACTIVAR_2FA', 'ACTIVAR_2FA'), ('DESACTIVAR_2FA', 'DESACTIVAR_2FA')], max_length=30),
        ),
    ]
