# Generated by Django 6.0 on 2026-08-19 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_alter_bitacora_accion'),
        ('core', '0012_permisos_tema_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_eventos', to='core.centroeducativo'),
        ),
    ]
