# Generated by Django 6.0 on 2026-01-08 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocentro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='anioescolar',
            unique_together={('centro', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='centroproveedor',
            unique_together={('proveedor', 'centro')},
        ),
        migrations.AlterUniqueTogether(
            name='usuariocentro',
            unique_together={('usuario', 'centro')},
        ),
    ]
