# Generated by Django 6.0 on 2026-05-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncentro',
            name='modulo_asistencia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='modulo_biblioteca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='modulo_cafeteria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='modulo_caja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='modulo_inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='modulo_mensajeria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='modulo_nomina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='modulo_reportes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='modulo_transporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='permitir_facturacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='permitir_pago_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='permitir_qr_asistencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='usar_biometrico',
            field=models.BooleanField(default=False),
        ),
    ]
