# Generated by Django 6.0 on 2026-05-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracioncentro_modulo_asistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncentro',
            name='tipo_pago_nomina',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('semanal', 'Semanal')], default='mensual', max_length=20),
        ),
    ]
