# Generated by Django 6.0 on 2026-06-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracioncentro_tipo_pago_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='anioescolar',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
