# Generated by Django 6.0 on 2026-08-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_anioescolar_cerrado'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='anioescolar',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('centro',), name='unique_active_year_per_center'),
        ),
    ]
