# Generated by Django 6.0 on 2026-08-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_anioescolar_unique_active_year_per_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncentro',
            name='facturacion_itbis',
            field=models.BooleanField(default=False, help_text='Activa el desglose de ITBIS (18%) en las facturas'),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='rnc',
            field=models.CharField(blank=True, help_text='RNC del centro para las facturas fiscales', max_length=11),
        ),
    ]
