# Generated by Django 6.0 on 2026-08-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracioncentro_facturacion_itbis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncentro',
            name='modulo_certificados',
            field=models.BooleanField(default=False, help_text='Activa las solicitudes de certificados/constancias en línea'),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='precio_certificado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de cada certificado/constancia solicitado', max_digits=10),
        ),
    ]
