# Generated by Django 6.0 on 2026-08-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuracioncentro_modulo_certificados_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='anioescolar',
            index=models.Index(fields=['centro', 'activo'], name='anio_centro_activo'),
        ),
    ]
