# Generated by Django 6.0 on 2026-08-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_anioescolar_anio_centro_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncentro',
            name='email_clave',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Contraseña de correo'),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='email_puerto',
            field=models.PositiveIntegerField(default=587, help_text='587 (TLS) o 465 (SSL)', verbose_name='Puerto SMTP'),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='email_remitente',
            field=models.EmailField(blank=True, default='', help_text='Dirección desde la que llegan los correos.', max_length=254, verbose_name='Correo remitente (From)'),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='email_servidor',
            field=models.CharField(blank=True, default='', help_text='Ej: smtp.gmail.com', max_length=200, verbose_name='Servidor SMTP'),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='email_ssl',
            field=models.BooleanField(default=False, help_text='Conexión segura SSL (puerto 465).', verbose_name='Usar SSL'),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='email_tls',
            field=models.BooleanField(default=True, help_text='Conexión segura TLS (puerto 587). Quitar si usas SSL (465).', verbose_name='Usar TLS'),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='email_usuario',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Usuario de correo'),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='whatsapp_remitente',
            field=models.CharField(blank=True, default='', help_text='Opcional. Número o ID del remitente que envía los mensajes.', max_length=100, verbose_name='Remitente WhatsApp (from)'),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='whatsapp_token',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Token del gateway WhatsApp'),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='whatsapp_url',
            field=models.CharField(blank=True, default='', help_text='Endpoint que recibe el POST JSON (Twilio, Meta Cloud API, etc.).', max_length=300, verbose_name='URL del gateway WhatsApp'),
        ),
    ]
