# Generated by Django 6.0 on 2026-08-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_configuracioncentro_email_clave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncentro',
            name='email_clave',
            field=models.CharField(blank=True, default='', help_text="Gmail/Outlook: usa una 'clave de aplicación' (app password) generada en la cuenta, NO la contraseña normal. Ej: xxxx xxxx xxxx xxxx", max_length=300, verbose_name='Contraseña / clave de aplicación (app password)'),
        ),
    ]
