# Generated by Django 6.0 on 2026-08-19 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_configuracioncentro_email_clave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='centroeducativo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo del centro educativo (se muestra en sidebar, login, PDFs)', null=True, upload_to='centros/logos/'),
        ),
        migrations.CreateModel(
            name='PermisoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(help_text='Nombre de la URL en Django (ej: estudiante_list, nomina:dashboard)', max_length=150, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripción legible de la página', max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, la regla no se aplica')),
                ('roles_permitidos', models.ManyToManyField(blank=True, help_text='Roles que pueden acceder a esta página', related_name='permisos_pagina', to='core.rolcentro')),
                ('usuarios_permitidos', models.ManyToManyField(blank=True, help_text='Usuarios individuales con acceso (además de los roles)', related_name='permisos_pagina_directos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de página',
                'verbose_name_plural': 'Permisos de página',
                'ordering': ['url_name'],
            },
        ),
        migrations.CreateModel(
            name='TemaCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Por defecto', help_text='Nombre del tema (ej: Azul, Verde, Morado)', max_length=50)),
                ('color_primario', models.CharField(default='#4f46e5', help_text='Color principal (sidebar, botones, headers)', max_length=7)),
                ('color_secundario', models.CharField(default='#6366f1', help_text='Color secundario (hover, acentos)', max_length=7)),
                ('color_acento', models.CharField(default='#818cf8', help_text='Color de acento (secciones, badges)', max_length=7)),
                ('color_texto', models.CharField(default='#111827', help_text='Color del texto principal', max_length=7)),
                ('color_fondo', models.CharField(default='#f5f7fb', help_text='Color de fondo del body', max_length=7)),
                ('color_fondo_sidebar', models.CharField(default='#312e81', help_text='Color de fondo del sidebar', max_length=7)),
                ('color_texto_sidebar', models.CharField(default='#c7d2fe', help_text='Color del texto en el sidebar', max_length=7)),
                ('color_borde', models.CharField(default='#e5e7eb', help_text='Color de bordes y separadores', max_length=7)),
                ('centro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tema', to='core.centroeducativo')),
            ],
            options={
                'verbose_name': 'Tema del centro',
                'verbose_name_plural': 'Temas de centros',
            },
        ),
    ]
