# Generated by Django 6.0 on 2026-08-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_permisos_tema_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='temacentro',
            name='color_advertencia',
            field=models.CharField(default='#f59e0b', help_text='Color para advertencias, warnings amarillos', max_length=7),
        ),
        migrations.AddField(
            model_name='temacentro',
            name='color_exito',
            field=models.CharField(default='#16a34a', help_text='Color para éxito, badges verdes, pagos', max_length=7),
        ),
        migrations.AddField(
            model_name='temacentro',
            name='color_peligro',
            field=models.CharField(default='#dc2626', help_text='Color para errores, danger, alertas rojas', max_length=7),
        ),
    ]
