# Generated by Django 6.0 on 2026-08-24 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tema_color_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreAnio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('totales', models.JSONField(default=dict)),
                ('deudores', models.JSONField(default=list)),
                ('total_deuda', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reabierto', models.BooleanField(default=False)),
                ('motivo_reapertura', models.TextField(blank=True)),
                ('fecha_reapertura', models.DateTimeField(blank=True, null=True)),
                ('anio_escolar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cierre', to='core.anioescolar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_reapertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reaperturas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
