# Generated by Django 6.0 on 2026-08-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cierreanio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncentro',
            name='email_api_key',
            field=models.CharField(blank=True, default='', help_text='API Key de Resend o SendGrid, según el proveedor elegido.', max_length=300, verbose_name='API Key del proveedor'),
        ),
        migrations.AddField(
            model_name='configuracioncentro',
            name='email_proveedor',
            field=models.CharField(choices=[('smtp_gmail', 'Gmail / Google Workspace (SMTP)'), ('smtp_outlook', 'Outlook / Microsoft 365 (SMTP)'), ('resend', 'Resend (API)'), ('sendgrid', 'SendGrid (API)'), ('consola', 'Ninguno (modo consola / desarrollo)')], default='consola', help_text='Elige cómo se envían los correos de este centro. Si tu hosting bloquea SMTP (ej. Render plan gratuito), usa Resend o SendGrid.', max_length=20, verbose_name='Proveedor de correo'),
        ),
    ]
