# Generated by Django 6.0 on 2026-08-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_agregar_proveedor_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncentro',
            name='email_proveedor',
            field=models.CharField(choices=[('smtp_gmail', 'Gmail / Google Workspace (SMTP)'), ('smtp_outlook', 'Outlook / Microsoft 365 (SMTP)'), ('smtp_otro', 'Otro servidor SMTP (personalizado)'), ('resend', 'Resend (API)'), ('sendgrid', 'SendGrid (API)'), ('consola', 'Ninguno (modo consola / desarrollo)')], default='consola', help_text='Elige cómo se envían los correos de este centro. Si tu hosting bloquea SMTP (ej. Render plan gratuito), usa Resend o SendGrid.', max_length=20, verbose_name='Proveedor de correo'),
        ),
    ]
