# Generated by Django 6.0 on 2026-08-30 01:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunicaciones', '0003_comunicado'),
        ('core', '0016_alter_configuracioncentro_email_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inasistencias', 'Inasistencias consecutivas'), ('notas_rojas', 'Notas en rojo'), ('pagos_vencidos', 'Pagos vencidos'), ('cumpleanos', 'Cumpleaños')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('ambos', 'Correo y WhatsApp')], default='email', max_length=10)),
                ('total_destinatarios', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automatizaciones', to='comunicaciones.campania')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_automaticas', to='core.centroeducativo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación automática',
                'verbose_name_plural': 'Notificaciones automáticas',
                'ordering': ['-created_at'],
            },
        ),
    ]
