# Generated by Django 6.0 on 2026-05-27 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_configuracioncentro_tipo_pago_nomina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('porcentaje_empleado', models.DecimalField(decimal_places=2, default=2.87, max_digits=5)),
                ('porcentaje_empresa', models.DecimalField(decimal_places=2, default=7.1, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ARS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('porcentaje_empleado', models.DecimalField(decimal_places=2, default=3.04, max_digits=5)),
                ('porcentaje_empresa', models.DecimalField(decimal_places=2, default=7.09, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('es_porcentaje', models.BooleanField(default=True)),
                ('obligatorio', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('obligatorio', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_pago', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('semanal', 'Semanal')], default='mensual', max_length=20)),
                ('activo_nomina', models.BooleanField(default=True)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('afp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.afp')),
                ('ars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.ars')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.cargo')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.centroeducativo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_nomina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('numero_periodo', models.IntegerField(default=1)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
                ('nomina_generada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.centroeducativo')),
            ],
            options={
                'ordering': ['-anio', '-mes', '-numero_periodo'],
                'unique_together': {('centro', 'anio', 'mes', 'numero_periodo')},
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('GENERADA', 'Generada'), ('REVISADA', 'Revisada'), ('APROBADA', 'Aprobada'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='GENERADA', max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.configuracionnomina')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas_generadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.periodonomina')),
            ],
            options={
                'unique_together': {('periodo', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='DescuentoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='nomina.nomina')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.tipodescuento')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_fijos', to='nomina.configuracionnomina')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.tipodescuento')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='nomina.nomina')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.tipoingreso')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_fijos', to='nomina.configuracionnomina')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.tipoingreso')),
            ],
        ),
    ]
