# Generated by Django 6.0 on 2026-01-08 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacurricular',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.centroeducativo'),
        ),
        migrations.AddField(
            model_name='areacompetencia',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.areacurricular'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.areacurricular'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.centroeducativo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura'),
        ),
    ]
