# Generated by Django 6.0 on 2026-01-08 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('core', '0001_initial'),
        ('docentes', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.inscripcion'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.competencia'),
        ),
        migrations.AddField(
            model_name='areacompetencia',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.competencia'),
        ),
        migrations.AddField(
            model_name='docentemateria',
            name='anio_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anioescolar'),
        ),
        migrations.AddField(
            model_name='docentemateria',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura'),
        ),
        migrations.AddField(
            model_name='docentemateria',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.docente'),
        ),
        migrations.AddField(
            model_name='docentemateria',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grado'),
        ),
        migrations.AddField(
            model_name='gradoasignatura',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura'),
        ),
        migrations.AddField(
            model_name='gradoasignatura',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grado'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.centroeducativo'),
        ),
        migrations.AddField(
            model_name='grado',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.nivel'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='anio_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anioescolar'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.centroeducativo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.periodo'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grado'),
        ),
        migrations.AddField(
            model_name='docentemateria',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.seccion'),
        ),
        migrations.AlterUniqueTogether(
            name='gradoasignatura',
            unique_together={('grado', 'asignatura')},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('inscripcion', 'asignatura', 'competencia', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='docentemateria',
            unique_together={('docente', 'asignatura', 'grado', 'seccion', 'anio_escolar')},
        ),
    ]
