# Generated by Django 6.0 on 2026-01-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='periodo',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodo',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
