# Generated by Django 6.0 on 2026-01-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alter_periodo_options_periodo_cerrado_and_more'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='docentemateria',
            unique_together={('asignatura', 'grado', 'seccion', 'anio_escolar')},
        ),
    ]
