# Generated by Django 6.0 on 2026-08-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_docentemateria_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['nivel', 'orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='grado',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
