# Generated by Django 6.0 on 2026-08-06 01:52

from django.db import migrations


def asignar_orden(apps, schema_editor):
    Grado = apps.get_model('academico', 'Grado')

    for grado in Grado.objects.all().order_by('id'):
        grado.orden = grado.id
        grado.save(update_fields=['orden'])


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_grado_options_grado_orden'),
    ]

    operations = [
        migrations.RunPython(asignar_orden, migrations.RunPython.noop),
    ]
