# Generated by Django 6.0 on 2026-08-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_asignar_orden_grados'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='tipo',
            field=models.CharField(choices=[('inicial', 'Nivel Inicial'), ('primaria', 'Nivel Primario'), ('secundaria', 'Nivel Secundario')], default='primaria', max_length=20, verbose_name='Tipo de plantilla'),
        ),
    ]
