# Generated by Django 6.0 on 2026-08-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_estructura_minerd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={'ordering': ['nivel', 'nombre']},
        ),
        migrations.AddField(
            model_name='competencia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competencia',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='academico.nivel', verbose_name='Nivel'),
        ),
        migrations.AlterUniqueTogether(
            name='competencia',
            unique_together={('nivel', 'nombre')},
        ),
    ]
