# Generated by Django 6.0 on 2026-08-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_periodo_catalogo_periodoanio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={'ordering': ['nivel', 'orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='competencia',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
