# Generated by Django 6.0 on 2026-08-09 04:24

from django.db import migrations

ORDEN_POR_NOMBRE = {
    'Comunicativa': 1,
    'Pensamiento Lógico, Creativo y Crítico y Resolución de Problemas': 2,
    'Científica y Tecnológica y Ambiental y de la Salud': 3,
    'Ética y Ciudadana y Desarrollo Personal y Espiritual': 4,
}


def seed_orden(apps, schema_editor):
    Competencia = apps.get_model('academico', 'Competencia')
    for nombre, orden in ORDEN_POR_NOMBRE.items():
        Competencia.objects.filter(
            nombre__endswith=nombre,
        ).update(orden=orden)


def unseed_orden(apps, schema_editor):
    Competencia = apps.get_model('academico', 'Competencia')
    Competencia.objects.filter(orden__gt=0).update(orden=0)


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_alter_competencia_options_competencia_orden'),
    ]

    operations = [
        migrations.RunPython(seed_orden, unseed_orden),
    ]
