# Generated by Django 6.0 on 2026-08-11 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_seed_orden_competencias'),
        ('core', '0007_configuracioncentro_facturacion_itbis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranjaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 1ra hora, Recreo, 3ra hora', max_length=80)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('orden', models.PositiveIntegerField(default=1)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franjas_horarias', to='core.centroeducativo')),
            ],
            options={
                'ordering': ['orden', 'hora_inicio'],
                'unique_together': {('centro', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.docentemateria')),
                ('franja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='academico.franjahoraria')),
            ],
            options={
                'ordering': ['dia_semana', 'franja__orden'],
                'unique_together': {('asignacion', 'dia_semana', 'franja')},
            },
        ),
    ]
