# Generated by Django 6.0 on 2026-08-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0016_franjahoraria_horarioclase'),
        ('core', '0009_anioescolar_anio_centro_activo'),
        ('docentes', '0003_docente_foto'),
        ('estudiantes', '0015_historialclinicoestudiante_registrosalud'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['inscripcion'], name='cal_inscripcion'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['periodo'], name='cal_periodo'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['asignatura'], name='cal_asignatura'),
        ),
        migrations.AddIndex(
            model_name='docentemateria',
            index=models.Index(fields=['grado', 'seccion', 'anio_escolar'], name='dm_grado_seccion_anio'),
        ),
        migrations.AddIndex(
            model_name='docentemateria',
            index=models.Index(fields=['docente', 'anio_escolar'], name='dm_docente_anio'),
        ),
        migrations.AddIndex(
            model_name='periodoanio',
            index=models.Index(fields=['anio_escolar'], name='pa_anio'),
        ),
    ]
