# Generated by Django 6.0 on 2026-08-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_competencias_4_por_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='origen',
            field=models.CharField(choices=[('docente', 'Docente'), ('sistema', 'Sistema (cierre forzado)')], default='docente', help_text="Quién registró la nota. Las notas 'Sistema' fueron puestas en 0 automáticamente al forzar un cierre de período.", max_length=10, verbose_name='Origen de la nota'),
        ),
    ]
