# Generated by Django 6.0 on 2026-08-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_calificacion_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='es_extraordinario',
            field=models.BooleanField(default=False),
        ),
    ]
