# Generated by Django 6.0 on 2026-08-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0020_periodo_extraordinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='capacidad_max',
            field=models.PositiveIntegerField(blank=True, help_text='Dejar vacío para sin límite.', null=True),
        ),
    ]
