# Generated by Django 6.0 on 2026-08-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0021_seccion_capacidad_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='nota_minima_aprobacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota mínima de aprobación específica del nivel (ej. 65 Primaria, 70 Secundaria). Si se deja vacío, se usa el valor general del centro.', max_digits=5, null=True),
        ),
    ]
