# Generated by Django 6.0 on 2026-08-07 04:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0004_crear_caja_por_defecto'),
        ('core', '0006_anioescolar_unique_active_year_per_center'),
        ('estudiantes', '0012_alter_estudiante_modalidad_salida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('letra', models.CharField(help_text='Prefijo alfabético del NCF (01→A, 02→B, 03→C...)', max_length=2)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de comprobante',
                'verbose_name_plural': 'Tipos de comprobante',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncf', models.CharField(blank=True, help_text='Número de comprobante fiscal; vacío si no es factura fiscal', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('itbis', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aplica_itbis', models.BooleanField(default=False, help_text='Indica si la factura desglosa ITBIS (18%)')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='core.centroeducativo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='estudiantes.estudiante')),
                ('pago', models.OneToOneField(blank=True, help_text='Pago de caja que origina esta factura', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='caja.pago')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipocomprobante')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.conceptopago')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.factura')),
            ],
        ),
        migrations.CreateModel(
            name='SecuenciaNCF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencias_ncf', to='core.centroeducativo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipocomprobante')),
            ],
            options={
                'verbose_name': 'Secuencia NCF',
                'verbose_name_plural': 'Secuencias NCF',
                'unique_together': {('centro', 'tipo')},
            },
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(condition=models.Q(('ncf__gt', '')), fields=('centro', 'ncf'), name='unique_ncf_por_centro'),
        ),
    ]
