# Generated by Django 6.0 on 2026-08-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_seed_tipos_ecf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ncf',
            field=models.CharField(blank=True, help_text='Número de comprobante fiscal electrónico (e-NCF); vacío si no aplica', max_length=20),
        ),
        migrations.AlterField(
            model_name='tipocomprobante',
            name='letra',
            field=models.CharField(help_text='Serie del e-NCF: siempre E en comprobantes electrónicos', max_length=2),
        ),
    ]
