# Generated by Django 6.0 on 2026-08-06 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_anioescolar_unique_active_year_per_center'),
        ('estudiantes', '0007_alter_historialacademico_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('tardanza', 'Tardanza'), ('justificado', 'Justificado'), ('ausente', 'Ausente')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='estudiantes.inscripcion')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('inscripcion', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='DiaNoDocencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(help_text='Ej: Feriado nacional, día de asueto, actividad institucional.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_no_docencia', to='core.anioescolar')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_no_docencia', to='core.centroeducativo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('centro', 'fecha')},
            },
        ),
    ]
