# Generated by Django 6.0 on 2026-08-11 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        ('estudiantes', '0016_estudiante_est_centro_estudiante_est_centro_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asistenciaestudiante',
            index=models.Index(fields=['inscripcion'], name='asist_inscripcion'),
        ),
        migrations.AddIndex(
            model_name='asistenciaestudiante',
            index=models.Index(fields=['fecha', 'estado'], name='asist_fecha_estado'),
        ),
    ]
