# Generated by Django 6.0 on 2026-08-14 02:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0017_calificacion_cal_inscripcion_and_more'),
        ('caja', '0006_pago_voucher'),
        ('core', '0009_anioescolar_anio_centro_activo'),
        ('tutores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(help_text='Asunto del correo. En WhatsApp se usa como encabezado.', max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(help_text='Contenido de la comunicación. Puedes usar {{tutor}} para el nombre del tutor y {{estudiante}} para el nombre del estudiante.', verbose_name='Mensaje')),
                ('canal', models.CharField(choices=[('email', 'Correo electrónico'), ('whatsapp', 'WhatsApp'), ('ambos', 'Correo y WhatsApp')], default='email', max_length=10)),
                ('alcance', models.CharField(choices=[('todos', 'Todos los tutores'), ('grado', 'Tutores de un grado'), ('seleccion', 'Tutores seleccionados')], default='todos', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('parcial', 'Enviada con errores'), ('fallida', 'Fallida')], default='borrador', max_length=20)),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanias', to='core.centroeducativo')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grado', models.ForeignKey(blank=True, help_text='Solo se usan tutores de estudiantes inscritos en este grado durante el año activo.', null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.grado')),
                ('tutores', models.ManyToManyField(blank=True, related_name='campanias', to='tutores.tutor')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Correo electrónico'), ('whatsapp', 'WhatsApp'), ('ambos', 'Correo y WhatsApp')], max_length=10)),
                ('contacto', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('sin_contacto', 'Sin contacto')], default='enviado', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_pago', to='core.centroeducativo')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='caja.pago')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_pago', to='tutores.tutor')),
            ],
            options={
                'verbose_name': 'Notificación de pago',
                'verbose_name_plural': 'Notificaciones de pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestinatarioCampania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Correo electrónico'), ('whatsapp', 'WhatsApp'), ('ambos', 'Correo y WhatsApp')], max_length=10)),
                ('contacto', models.CharField(blank=True, help_text='Email o teléfono usado para el envío.', max_length=150)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido'), ('sin_contacto', 'Sin contacto')], default='pendiente', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='comunicaciones.campania')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanias_recibidas', to='tutores.tutor')),
            ],
            options={
                'verbose_name': 'Destinatario de campaña',
                'verbose_name_plural': 'Destinatarios de campaña',
                'unique_together': {('campania', 'tutor', 'canal')},
            },
        ),
    ]
