# Generated by Django 6.0 on 2026-08-20 03:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0001_initial'),
        ('core', '0013_tema_color_extra'),
        ('estudiantes', '0019_alter_documentoestudiante_estudiante'),
        ('tutores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionPagoVencida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Correo electrónico'), ('whatsapp', 'WhatsApp'), ('ambos', 'Correo y WhatsApp')], max_length=10)),
                ('contacto', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('sin_contacto', 'Sin contacto')], default='enviado', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('monto_vencido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_vencimiento', to='core.centroeducativo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_vencimiento', to='estudiantes.estudiante')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_vencimiento', to='tutores.tutor')),
            ],
            options={
                'verbose_name': 'Notificación de vencimiento',
                'verbose_name_plural': 'Notificaciones de vencimiento',
                'ordering': ['-created_at'],
                'unique_together': {('centro', 'estudiante', 'tutor', 'fecha')},
            },
        ),
    ]
