# Generated by Django 6.0 on 2026-08-22 03:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_competencias_4_por_nivel'),
        ('comunicaciones', '0002_notificacionpagovencida'),
        ('core', '0013_tema_color_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('contenido', models.TextField(help_text='Texto del comunicado que veran estudiantes y tutores.', verbose_name='Contenido')),
                ('alcance', models.CharField(choices=[('todos', 'Todo el centro'), ('seccion', 'Una seccion')], default='todos', max_length=10)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicacion')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Opcional: despues de esta fecha deja de mostrarse.', null=True, verbose_name='Vence el')),
                ('fijado', models.BooleanField(default=False, help_text='Los comunicados fijados aparecen primero.', verbose_name='Fijado arriba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_publicados', to=settings.AUTH_USER_MODEL)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='core.centroeducativo')),
                ('seccion', models.ForeignKey(blank=True, help_text='Solo se usa cuando el alcance es una seccion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunicados', to='academico.seccion')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-fijado', '-fecha_publicacion'],
            },
        ),
    ]
