# Generated by Django 6.0 on 2026-01-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
