# Generated by Django 5.1.2 on 2026-01-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_es_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('docente', 'Docente'), ('estudiante', 'Estudiante')], default=1, editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
