# Generated by Django 6.0 on 2026-01-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_super_admin',
        ),
        migrations.AddField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(default='N/A', max_length=150, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(default='N/A', max_length=150, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('docente', 'Docente'), ('estudiante', 'Estudiante'), ('director', 'Director')], editable=False, max_length=20),
        ),
    ]
