# Generated by Django 6.0 on 2026-04-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_es_super_admin_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('docente', 'Docente'), ('estudiante', 'Estudiante'), ('director', 'Director')], max_length=20),
        ),
    ]
