# Generated by Django 6.0 on 2026-08-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('docente', 'Docente'), ('estudiante', 'Estudiante'), ('director', 'Director'), ('cajero', 'Cajero')], max_length=20),
        ),
    ]
