# Generated by Django 6.0 on 2026-08-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_debe_cambiar_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/', verbose_name='Foto'),
        ),
    ]
