# Generated by Django 6.0 on 2026-08-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('docente', 'Docente'), ('estudiante', 'Estudiante'), ('director', 'Director'), ('cajero', 'Cajero'), ('tutor', 'Tutor')], max_length=20),
        ),
    ]
