# Generated by Django 6.0 on 2026-08-18 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_alter_configuracioncentro_email_clave'),
        ('estudiantes', '0017_alter_inscripcion_estudiante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dato', models.CharField(choices=[('datos_personales', 'Datos Personales'), ('datos_academicos', 'Datos Académicos'), ('datos_clinicos', 'Datos Clínicos'), ('datos_tutor', 'Datos del Tutor'), ('historial_academico', 'Historial Académico'), ('constancia', 'Constancia/Certificado'), ('estadistico', 'Estadístico (anónimo)')], max_length=30)),
                ('accion', models.CharField(choices=[('anonimizacion', 'Anonimización'), ('eliminacion', 'Eliminación'), ('exportacion_archivo', 'Exportación a archivo')], max_length=20)),
                ('registros_afectados', models.PositiveIntegerField(default=0)),
                ('detalle', models.JSONField(default=dict)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('ejecutado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_retencion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Retención',
                'verbose_name_plural': 'Registros de Retención',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoInformado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_nombre', models.CharField(max_length=200)),
                ('tutor_cedula', models.CharField(max_length=20)),
                ('tutor_parentesco', models.CharField(max_length=100)),
                ('acepta_datos_personales', models.BooleanField(default=False)),
                ('acepta_datos_academicos', models.BooleanField(default=False)),
                ('acepta_datos_clinicos', models.BooleanField(default=False)),
                ('acepta_comunicaciones', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_revocacion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('ip_firma', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_firma', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='core.anioescolar')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='core.centroeducativo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Consentimiento Informado',
                'verbose_name_plural': 'Consentimientos Informados',
                'ordering': ['-fecha_firma'],
                'indexes': [models.Index(fields=['estudiante', 'activo'], name='consent_est_act'), models.Index(fields=['centro', 'anio_escolar'], name='consent_centro_anio')],
            },
        ),
        migrations.CreateModel(
            name='RegistroAccesoDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dato', models.CharField(choices=[('datos_personales', 'Datos Personales'), ('datos_academicos', 'Datos Académicos'), ('datos_clinicos', 'Datos Clínicos'), ('datos_tutor', 'Datos del Tutor'), ('historial_academico', 'Historial Académico'), ('constancia', 'Constancia/Certificado'), ('estadistico', 'Estadístico (anónimo)')], max_length=30)),
                ('accion', models.CharField(choices=[('lectura', 'Lectura'), ('escritura', 'Escritura'), ('exportacion', 'Exportación'), ('eliminacion', 'Eliminación'), ('anonimizacion', 'Anonimización')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_datos', to='estudiantes.estudiante')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_datos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Acceso a Dato',
                'verbose_name_plural': 'Registros de Acceso a Datos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', 'fecha'], name='acceso_user_fecha'), models.Index(fields=['tipo_dato', 'fecha'], name='acceso_tipo_fecha'), models.Index(fields=['estudiante', 'fecha'], name='acceso_est_fecha')],
            },
        ),
    ]
