# Generated by Django 6.0 on 2026-01-08 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0003_initial'),
        ('core', '0002_initial'),
        ('estudiantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.grado'),
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.nivel'),
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.seccion'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='anio_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.anioescolar'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.centroeducativo'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.grado'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.seccion'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('estudiante', 'anio_escolar')},
        ),
    ]
