# Generated by Django 6.0 on 2026-06-04 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracioncentro_tipo_pago_nomina'),
        ('estudiantes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estado_final',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('retirado', 'Retirado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='promedio_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='historialacademico',
            name='anio_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.anioescolar'),
        ),
    ]
