# Generated by Django 6.0 on 2026-06-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_inscripcion_estado_final_inscripcion_fecha_cierre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialacademico',
            name='estado',
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
