# Generated by Django 6.0 on 2026-06-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_remove_historialacademico_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialacademico',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
