# Generated by Django 6.0 on 2026-06-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_historialacademico_cerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialacademico',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('retirado', 'Retirado')], default='aprobado', max_length=20),
        ),
    ]
