# Generated by Django 6.0 on 2026-08-06 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_historialacademico_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialacademico',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('retirado', 'Retirado'), ('sin_calificacion', 'Sin Calificación')], default='aprobado', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado_final',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('retirado', 'Retirado'), ('sin_calificacion', 'Sin Calificación')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to='estudiantes/documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
        ),
    ]
