# Generated by Django 6.0 on 2026-08-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_alter_historialacademico_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialacademico',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('recuperacion', 'Recuperación'), ('retirado', 'Retirado'), ('sin_calificacion', 'Sin Calificación')], default='aprobado', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado_final',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('recuperacion', 'Recuperación'), ('retirado', 'Retirado'), ('sin_calificacion', 'Sin Calificación')], default='pendiente', max_length=20),
        ),
    ]
