# Generated by Django 6.0 on 2026-08-07 01:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_anioescolar_unique_active_year_per_center'),
        ('estudiantes', '0009_normalizar_estados_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('observacion', 'Observación'), ('conducta', 'Conducta'), ('merito', 'Mérito / Reconocimiento'), ('amonestacion', 'Amonestación')], default='observacion', max_length=20)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_escolar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_estudiantes', to='core.anioescolar')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='estudiantes.estudiante')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
