# Generated by Django 6.0 on 2026-08-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0011_estudiante_modalidad_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='modalidad_salida',
            field=models.CharField(blank=True, choices=[('general', 'Modalidad General'), ('ciencias_letras', 'Ciencias y Letras'), ('ciencias_fisicas_matematicas', 'Ciencias Físicas y Matemáticas'), ('ciencias_fisicas_naturales', 'Ciencias Físicas y Naturales'), ('filosofia_letras', 'Filosofía y Letras')], help_text='Modalidad de salida del bachiller (solo Nivel Secundario).', max_length=50, null=True, verbose_name='Modalidad de salida'),
        ),
    ]
