# Generated by Django 6.0 on 2026-08-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0012_alter_estudiante_modalidad_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes/fotos/', verbose_name='Foto'),
        ),
    ]
