# Generated by Django 6.0 on 2026-08-11 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0013_estudiante_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo_certificado', models.CharField(choices=[('constancia_estudio', 'Constancia de Estudios'), ('record_notas', 'Récord de Notas'), ('constancia_conducta', 'Constancia de Conducta')], default='constancia_estudio', max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('pagada', 'Pagada'), ('entregada', 'Entregada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('online', 'En línea')], default='efectivo', max_length=20)),
                ('referencia_pago', models.CharField(blank=True, help_text='Referencia de la pasarela o del comprobante de pago.', max_length=100)),
                ('pagado', models.BooleanField(default=False)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('rechazo_motivo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_aprobados', to=settings.AUTH_USER_MODEL)),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_entregados', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_certificados', to='estudiantes.estudiante')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_certificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
