# Generated by Django 6.0 on 2026-08-11 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0014_solicitudcertificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinicoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('desconocido', 'No especificado')], default='desconocido', max_length=20)),
                ('alergias', models.TextField(blank=True, help_text='Alergias a medicamentos, alimentos u otros.')),
                ('condiciones_medicas', models.TextField(blank=True, help_text='Enfermedades crónicas, condiciones o diagnósticos relevantes.')),
                ('medicamentos_habituales', models.TextField(blank=True, help_text='Medicamentos que toma de forma habitual.')),
                ('vacunas', models.TextField(blank=True, help_text='Vacunas y dosis (opcional).')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=200)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20)),
                ('contacto_emergencia_parentesco', models.CharField(blank=True, max_length=100)),
                ('contacto_emergencia_secundario_nombre', models.CharField(blank=True, max_length=200)),
                ('contacto_emergencia_secundario_telefono', models.CharField(blank=True, max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Cualquier otra información relevante para emergencias.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_clinico', to='estudiantes.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('enfermedad', 'Enfermedad'), ('accidente', 'Accidente'), ('emergencia', 'Emergencia'), ('atencion', 'Atención general'), ('vacuna', 'Vacuna')], default='atencion', max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('atencion_proporcionada', models.TextField(blank=True, help_text='Qué se hizo o qué atención se prestó.')),
                ('medicamento', models.CharField(blank=True, help_text='Medicamento administrado o indicado.', max_length=200)),
                ('notificado_a_tutor', models.BooleanField(default=False, help_text='¿Se notificó al tutor/representante?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_salud', to='estudiantes.estudiante')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_salud', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
