# Generated by Django 6.0 on 2026-08-11 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0017_calificacion_cal_inscripcion_and_more'),
        ('core', '0009_anioescolar_anio_centro_activo'),
        ('estudiantes', '0015_historialclinicoestudiante_registrosalud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['centro'], name='est_centro'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['centro', 'estado'], name='est_centro_estado'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['centro', 'anio_escolar'], name='insc_centro_anio'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['estudiante'], name='insc_estudiante'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['estado_final'], name='insc_estado_final'),
        ),
        migrations.AddIndex(
            model_name='observacionestudiante',
            index=models.Index(fields=['estudiante'], name='obs_estudiante'),
        ),
        migrations.AddIndex(
            model_name='observacionestudiante',
            index=models.Index(fields=['anio_escolar'], name='obs_anio'),
        ),
        migrations.AddIndex(
            model_name='registrosalud',
            index=models.Index(fields=['estudiante'], name='rsalud_estudiante'),
        ),
    ]
