# Generated by Django 6.0 on 2026-08-18 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0016_estudiante_est_centro_estudiante_est_centro_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='estudiantes.estudiante'),
        ),
    ]
