# Generated by Django 6.0 on 2026-08-18 02:12

import seguridad.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0017_alter_inscripcion_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinicoestudiante',
            name='alergias',
            field=seguridad.fields.EncryptedTextField(blank=True, help_text='Alergias a medicamentos, alimentos u otros.'),
        ),
        migrations.AlterField(
            model_name='historialclinicoestudiante',
            name='condiciones_medicas',
            field=seguridad.fields.EncryptedTextField(blank=True, help_text='Enfermedades crónicas, condiciones o diagnósticos relevantes.'),
        ),
        migrations.AlterField(
            model_name='historialclinicoestudiante',
            name='contacto_emergencia_nombre',
            field=seguridad.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='historialclinicoestudiante',
            name='contacto_emergencia_parentesco',
            field=seguridad.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='historialclinicoestudiante',
            name='contacto_emergencia_secundario_nombre',
            field=seguridad.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='historialclinicoestudiante',
            name='contacto_emergencia_secundario_telefono',
            field=seguridad.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='historialclinicoestudiante',
            name='contacto_emergencia_telefono',
            field=seguridad.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='historialclinicoestudiante',
            name='medicamentos_habituales',
            field=seguridad.fields.EncryptedTextField(blank=True, help_text='Medicamentos que toma de forma habitual.'),
        ),
        migrations.AlterField(
            model_name='historialclinicoestudiante',
            name='observaciones',
            field=seguridad.fields.EncryptedTextField(blank=True, help_text='Cualquier otra información relevante para emergencias.'),
        ),
        migrations.AlterField(
            model_name='historialclinicoestudiante',
            name='vacunas',
            field=seguridad.fields.EncryptedTextField(blank=True, help_text='Vacunas y dosis (opcional).'),
        ),
    ]
