# Generated by Django 6.0 on 2026-08-18 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0018_alter_historialclinicoestudiante_alergias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estudiantes.estudiante'),
        ),
    ]
