# Generated by Django 6.0 on 2026-08-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0019_alter_documentoestudiante_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialacademico',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('recuperacion', 'Recuperación'), ('retirado', 'Retirado'), ('sin_calificacion', 'Sin Calificación'), ('promocion_condicional', 'Promoción Condicional')], default='aprobado', max_length=25),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado_final',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('recuperacion', 'Recuperación'), ('retirado', 'Retirado'), ('sin_calificacion', 'Sin Calificación'), ('promocion_condicional', 'Promoción Condicional')], default='pendiente', max_length=25),
        ),
    ]
