# Generated by Django 6.0 on 2026-08-06 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_sesioncaja_egreso_pago_sesion_asignacionconcepto'),
        ('core', '0006_anioescolar_unique_active_year_per_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='core.centroeducativo')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('centro', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='caja',
            field=models.ForeignKey(blank=True, help_text='Caja registradora sobre la que se abrió la sesión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='caja.caja'),
        ),
    ]
