# Generated by Django 6.0 on 2026-08-11 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_crear_caja_por_defecto'),
        ('core', '0009_anioescolar_anio_centro_activo'),
        ('estudiantes', '0016_estudiante_est_centro_estudiante_est_centro_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(fields=['centro', 'fecha'], name='egreso_centro_fecha'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['centro', 'fecha'], name='pago_centro_fecha'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estudiante'], name='pago_estudiante'),
        ),
    ]
