# Generated by Django 6.0 on 2026-08-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_egreso_egreso_centro_fecha_pago_pago_centro_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='voucher',
            field=models.CharField(blank=True, default='', help_text='Código de voucher del datáfono/Verifone (pago con tarjeta)', max_length=50),
        ),
    ]
