# Generated by Django 6.0 on 2026-08-16 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0018_competencias_4_por_nivel'),
        ('core', '0011_alter_configuracioncentro_email_clave'),
        ('estudiantes', '0016_estudiante_est_centro_estudiante_est_centro_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramoEdad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('edad_min', models.PositiveIntegerField()),
                ('edad_max', models.PositiveIntegerField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['edad_min', 'edad_max', 'nombre'],
                'unique_together': {('edad_min', 'edad_max')},
            },
        ),
        migrations.CreateModel(
            name='DestrezaCognitiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('atencion', 'Atención'), ('memoria', 'Memoria de trabajo'), ('lectura', 'Fluidez lectora'), ('comprension', 'Comprensión'), ('logica', 'Pensamiento lógico-matemático'), ('metacognicion', 'Metacognición y pensamiento crítico')], max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('tramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destrezas', to='entrenamiento.tramoedad')),
            ],
            options={
                'ordering': ['tramo', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('destrezas', models.ManyToManyField(blank=True, related_name='unidades', to='entrenamiento.destrezacognitiva')),
                ('tramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='entrenamiento.tramoedad')),
            ],
            options={
                'ordering': ['tramo', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_seg', models.PositiveIntegerField(default=0)),
                ('items_total', models.PositiveIntegerField(default=0)),
                ('aciertos', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('ipd', models.DecimalField(blank=True, decimal_places=2, help_text='Índice de Productividad Digital de la sesión (0-100).', max_digits=6, null=True)),
                ('estado', models.CharField(choices=[('en_progreso', 'En progreso'), ('completada', 'Completada'), ('abandonada', 'Abandonada')], default='en_progreso', max_length=20)),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_entrenamiento', to='core.anioescolar')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_entrenamiento', to='estudiantes.estudiante')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='entrenamiento.unidadentrenamiento')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanRefuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generado', models.DateField(auto_now_add=True)),
                ('generado_por', models.CharField(choices=[('auto', 'Automático'), ('docente', 'Docente'), ('orientador', 'Orientador'), ('ia', 'IA')], default='auto', max_length=20)),
                ('origen', models.CharField(choices=[('destrezas_bajas', 'Destrezas bajas'), ('alerta', 'Alerta'), ('adecuacion', 'Adecuación curricular'), ('manual', 'Manual')], default='destrezas_bajas', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_refuerzo', to='core.anioescolar')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_refuerzo', to='estudiantes.estudiante')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_refuerzo', to='entrenamiento.unidadentrenamiento')),
            ],
            options={
                'ordering': ['-fecha_generado'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('seleccion', 'Selección'), ('verdadero_falso', 'Verdadero / Falso'), ('completar', 'Completar'), ('secuencia', 'Secuencia / orden'), ('filtrado', 'Filtrado'), ('comprension', 'Comprensión de lectura'), ('calculo', 'Cálculo mental')], max_length=20)),
                ('dificultad', models.PositiveIntegerField(choices=[(1, 'Fácil'), (2, 'Media'), (3, 'Difícil'), (4, 'Muy difícil'), (5, 'Experto')], default=1)),
                ('enunciado', models.TextField()),
                ('texto', models.TextField(blank=True, help_text='Pasaje de lectura, opcional según el tipo.')),
                ('opciones', models.JSONField(blank=True, default=list, help_text='Opciones: [{"texto": "...", "correcta": false}]')),
                ('respuesta_correcta', models.TextField(blank=True, help_text='Respuesta cuando el tipo no usa opciones.')),
                ('tiempo_max_seg', models.PositiveIntegerField(default=60)),
                ('activo', models.BooleanField(default=True)),
                ('destreza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='entrenamiento.destrezacognitiva')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='entrenamiento.unidadentrenamiento')),
            ],
            options={
                'ordering': ['unidad', 'destreza', 'dificultad'],
            },
        ),
        migrations.CreateModel(
            name='ItemPlanRefuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('superado', 'Superado')], default='pendiente', max_length=20)),
                ('destreza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_refuerzo', to='entrenamiento.destrezacognitiva')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_refuerzo', to='entrenamiento.ejercicio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='entrenamiento.planrefuerzo')),
            ],
            options={
                'ordering': ['plan', 'orden'],
                'unique_together': {('plan', 'ejercicio')},
            },
        ),
        migrations.CreateModel(
            name='IntentoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acierto', models.BooleanField(default=False)),
                ('tiempo_respuesta_ms', models.PositiveIntegerField(default=0)),
                ('dificultad_aplicada', models.PositiveIntegerField(default=1)),
                ('respuesta_dada', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='entrenamiento.ejercicio')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='entrenamiento.sesionentrenamiento')),
            ],
            options={
                'indexes': [models.Index(fields=['ejercicio'], name='int_ejercicio')],
                'unique_together': {('sesion', 'ejercicio')},
            },
        ),
        migrations.CreateModel(
            name='MetricaCognitiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField()),
                ('ipd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentil_edad', models.DecimalField(decimal_places=2, help_text='Percentil respecto a la distribución del mismo tramo en el centro (0-100).', max_digits=5)),
                ('desglose', models.JSONField(default=dict, help_text='Por destreza: {destreza_id: {"aciertos": n, "errores": n, "tiempo_promedio_ms": n, "nivel": "...", "percentil": n}}')),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_cognitivas', to='core.anioescolar')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_cognitivas', to='estudiantes.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_cognitivas', to='academico.periodoanio')),
                ('tramo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrenamiento.tramoedad')),
            ],
            options={
                'ordering': ['-fecha_corte'],
                'unique_together': {('estudiante', 'anio_escolar', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoCognitivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('resultado', models.JSONField(default=dict, help_text='Por destreza: {destreza_id: {"aciertos": n, "errores": n, "nivel": "bajo"|"medio"|"alto"}}')),
                ('ipd', models.DecimalField(blank=True, decimal_places=2, help_text='Índice de Productividad Digital inicial (0-100).', max_digits=6, null=True)),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_cognitivos', to='core.anioescolar')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_cognitivos', to='estudiantes.estudiante')),
                ('tramo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrenamiento.tramoedad')),
            ],
            options={
                'indexes': [models.Index(fields=['estudiante', 'anio_escolar'], name='diag_est_anio')],
                'unique_together': {('estudiante', 'anio_escolar')},
            },
        ),
        migrations.AddIndex(
            model_name='destrezacognitiva',
            index=models.Index(fields=['categoria'], name='dc_categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='destrezacognitiva',
            unique_together={('tramo', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='unidadentrenamiento',
            unique_together={('tramo', 'numero')},
        ),
        migrations.AddIndex(
            model_name='sesionentrenamiento',
            index=models.Index(fields=['estudiante', 'fecha_inicio'], name='se_est_fecha'),
        ),
        migrations.AddIndex(
            model_name='sesionentrenamiento',
            index=models.Index(fields=['estudiante', 'anio_escolar'], name='se_est_anio'),
        ),
        migrations.AddIndex(
            model_name='ejercicio',
            index=models.Index(fields=['destreza', 'activo'], name='ej_destreza_activo'),
        ),
    ]
