# Generated by Django 6.0 on 2026-08-16 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_alter_configuracioncentro_email_clave'),
        ('estudiantes', '0016_estudiante_est_centro_estudiante_est_centro_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acceso', 'Adecuación de acceso'), ('no_significativa', 'Adecuación no significativa'), ('significativa', 'Adecuación significativa')], max_length=20)),
                ('origen', models.CharField(choices=[('cognitivo', 'Perfil cognitivo'), ('conductual', 'Conducta'), ('salud', 'Salud'), ('academico', 'Rendimiento académico'), ('otro', 'Otro')], default='cognitivo', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('objetivos', models.TextField()),
                ('estrategias', models.TextField(help_text='Estrategias y ajustes a implementar.')),
                ('seguimiento', models.TextField(blank=True)),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_pedagogicos', to='core.anioescolar')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_pedagogicos', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_pedagogicos', to='estudiantes.estudiante')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cognitivo', 'Cognitivo'), ('academico', 'Académico'), ('conductual', 'Conductual'), ('asistencia', 'Asistencia'), ('salud', 'Salud'), ('pago', 'Pago')], max_length=20)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('descripcion', models.TextField()),
                ('sugerencia', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('atendida', 'Atendida'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('atendida_en', models.DateTimeField(blank=True, null=True)),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.anioescolar')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_creadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='estudiantes.estudiante')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['estudiante', 'estado'], name='al_est_estado'), models.Index(fields=['tipo', 'estado'], name='al_tipo_estado')],
            },
        ),
        migrations.CreateModel(
            name='IntervencionPsicopedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('sesion', 'Sesión de orientación'), ('observacion', 'Observación'), ('evaluacion', 'Evaluación psicopedagógica'), ('derivacion', 'Derivación'), ('seguimiento', 'Seguimiento')], max_length=20)),
                ('objetivo', models.CharField(max_length=255)),
                ('estrategia', models.TextField(blank=True)),
                ('resultado', models.TextField(blank=True)),
                ('derivacion_a', models.CharField(blank=True, help_text='Especialista o servicio al que se deriva.', max_length=150)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='estudiantes.estudiante')),
                ('orientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['estudiante', 'fecha'], name='iv_est_fecha')],
            },
        ),
    ]
